export/urls.py
from django.urls import path

from export.views import protocol_list, protocol_address

app_name = 'export'
urlpatterns = [
    path('protocol_list/', protocol_list, name='protocol-list'),
    path('protocol_address/<int:protocol_id>/', protocol_address, name='protocol-address')
]

generators/urls.py
from django.urls import path, include
from .views import (config_generator,
                    create_generator,
                    detail_generator,
                    delete_generator,
                    save_generator,
                    ajax_generate,)

app_name = 'generators'
urlpatterns = [
    path('config/', config_generator, name='generator-config'),
    path('list/<str:success>/', config_generator, name='generator-config-success'),
    path('create/', create_generator, name='generator-create'),
    path('detail/<slug:use_area>/', detail_generator, name='generator-detail'),
    path('delete/<slug:use_area>/', delete_generator, name='generator-delete'),
    path('save/', save_generator, name='generator-save'),
    path('ajax_genarate/', ajax_generate, name='ajax-generate')
]

int_messages/urls.py
from django.urls import path, include
from .views import show_messages, create_message, detail_message, answer_message, close_topic, detail_alert

app_name = 'int_messages'
urlpatterns = [
    path('create/', create_message, name='message-create'),
    path('detail/<int:message_id>/<slug:parent_box>/', detail_message, name='message-detail'),
    path('alert_detail/<int:alert_id>/', detail_alert, name='alert-detail'),
    path('answer/', answer_message, name='message-answer'),
    path('close_message/<slug:ticket_id>/<str:parent_box>/', close_topic, name='topic-close'),
    path('show/<str:box>/<slug:type>/<slug:message>/', show_messages, name='message-list'),
]

tekhnoritm_web/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import start_app
from django.conf.urls.static import static
from django.conf import settings
from .views import ajax_alarms, ajax_mark_as_red
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', start_app, name='start-app'),
    path('favicon.ico', RedirectView.as_view(url='/static/custom/favicon.ico'), name='favicon'),
    path('order_control/', include('order_control.urls')),
    path('rpn_searcher/', include('rpn_searcher.urls')),
    path('archive/', include('archive.urls')),
    path('laboratory/', include('laboratory.urls')),
    path('inspection/', include('inspection.urls')),
    path('orders/', include('orders.urls')),
    path('references/', include('references.urls')),
    path('generators/', include('generators.urls')),
    path('int_messages/', include('int_messages.urls')),
    path('site_admin/', include('site_admin.urls')),
    path('accounts/', include('accounts.urls')),
    path('workflow/', include('workflow.urls')),
    path('export', include('export.urls')),
    path('alarms/', ajax_alarms, name='ajax-alarm'),
    path('marks/', ajax_mark_as_red, name='ajax-mark-as-red'),
    path('admin/', admin.site.urls),
    re_path(r'^celery-progress/', include('celery_progress.urls')),  # the endpoint is configurable
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

generators/models.py
from django.db import models
from django.urls import reverse
from django.db.models import Max

# Create your models here.


class Generator(models.Model):
    no = models.IntegerField(verbose_name='Текущий номер')
    gen_type = models.CharField(verbose_name='Префикс', max_length=32)
    year = models.CharField(verbose_name='Год', max_length=16)
    use_area = models.CharField(verbose_name='Область применения', max_length=128, primary_key=True)

    def get_absolute_url(self):
        return reverse("generators:generator-detail", args=(self.use_area,))

    def __str__(self):
        return '%s%s%s' % (self.no, self.gen_type, self.year)

    @staticmethod
    def get_last(use_area):
        obj = Generator.objects.filter(use_area=use_area).first()
        return obj

    @staticmethod
    def set_new(use_area):
        last_obj = Generator.objects.filter(use_area=use_area).first()
        last_obj.no = last_obj.no + 1
        last_obj.save()
        return last_obj

generators/forms.py
from django import forms
from .models import Generator


class GeneratorForm(forms.ModelForm):
    class Meta:
        model = Generator
        fields = ['use_area', 'no', 'gen_type', 'year']

generators/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import GeneratorForm
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import Generator

# Create your views here.


def config_generator(request, success=None):
    if success:
        context = {'success': success}
    else:
        context = {}
    gens = Generator.objects.all()
    context['generators'] = gens
    return render(request, 'generators/generator_config.html', context)


def create_generator(request):
    if request.method == 'POST':
        form = GeneratorForm(request.POST)
        if form.is_valid():
            form.save()
            context = {
                'success': 'Генератор был успешно добавлен!',
            }
            return HttpResponseRedirect(reverse('generators:generator-config-success', kwargs=context))
    else:
        form = GeneratorForm()
    return render(request, 'generators/generator_create.html', {'form': form})


def detail_generator(request, use_area):
    obj = get_object_or_404(Generator, use_area=use_area)
    objForm = GeneratorForm(instance=obj)
    context = {
        'instance': obj.use_area,
        'form': objForm,
    }
    return render(request, 'generators/generator_detail.html', context)


def delete_generator(request, use_area):
    obj = get_object_or_404(Generator, use_area=use_area)
    obj.delete()
    context = {
        'success': 'Генератор был успешно удален!',
    }
    return HttpResponseRedirect(reverse('generators:generator-config-success', kwargs=context))


def save_generator(request):
    context = {}
    if request.method == 'POST':
        generator_form = GeneratorForm(request.POST, instance=Generator.objects.get(pk=request.POST['use_area']))
        if generator_form.is_valid():
            generator_form.save()
            context = {
                'success': 'Генератор был успешно отредактирован!',
            }
            return HttpResponseRedirect(reverse('generators:generator-config-success', kwargs=context))
    return render(request, 'generators/generator_detail.html', context)


def ajax_generate(request):
    use_area = request.GET['use_area']
    if use_area:
        new_obj = Generator.set_new(use_area)
        return HttpResponse(str(new_obj))
    else:
        return HttpResponse('')

generators/templates/generators/generator_config.html
<!-- generator_config.html -->

{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800">Управление генераторами номеров</h1>
          <p class="mb-4">Для редактирования записей необходимо иметь права "Site_Administrator"</p>
          {% if success %}
          <p class="mb-4 text-primary">{{ success }}</p>
          {% endif %}
          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Полная выборка генераторов</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Область примененения</th>
                      <th>Текущий номер</th>
                      <th>Профекс (Код)</th>
                      <th>Префикс (Год)</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for instance in generators %}
                    <tr>
                        <td><a href="{{ instance.get_absolute_url }}"><strong>{{ instance.use_area }}</strong></a></td>
                        <td>{{ instance.no }}</td>
                        <td>{{ instance.gen_type }}</td>
                        <td>{{ instance.year }}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <a href="{% url 'generators:generator-create' %}" class="btn btn-primary btn-user btn-block">
            Добавить новый
          </a>

        </div>
        <!-- /.container-fluid -->

{% endblock content %}

generators/templates/generators/generator_create.html
<!-- generator_create.html -->

{% extends 'base.html' %}
{% load static %}

{% block content %}

  <div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Создание нового генератора!</h1>
              </div>
              <form class="user" name="form" id="main_form" method="post">
                  {% csrf_token %}
                  {% include 'bs4_form.html' %}

                <a href="javascript:;" onclick="document.getElementById('main_form').submit();" class="btn btn-primary btn-user btn-block">
                  Создать
                </a>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

{% endblock content %}

generators/templates/generators/generator_detail.html
<!-- generator_detail.html -->

{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Редактор генератора</h1>
            <a href="{% url 'int_messages:message-create' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Написать сообщение</a>
          </div>
<!-- End of Page Heading -->

<div class="container">
    <div class="row">
        <div class="card o-hidden border-0 shadow-lg my-5">
              <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                  <div class="col-lg-12">
                    <div class="p-5">
                      <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-4">Выбран генератор</h1>
                      </div>
                        <form class="user" id="main_form" method="POST" name="form" action="/generators/save/" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'bs4_form.html' with form=form %}

                            <a href="javascript:;" onclick="document.getElementById('main_form').submit();" class="btn btn-primary btn-user btn-block">
                              Сохранить
                            </a>
                            <a class="dropdown-item" href="{% url 'generators:generator-delete' use_area=instance %}" data-toggle="modal" data-target="#deleteModal">
                                <i class="fas fa-calendar-times-o fa-sm fa-fw mr-2 text-warning"></i>
                                Удалить
                            </a>
                        </form>
                    </div>
                  </div>
                </div>
              </div>
        </div>
    </div>
</div>

<!-- Delete Modal-->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Удалить генератор?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Удаление генератора отразится на генерации документов. Удалить?</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Отмена</button>
          <a class="btn btn-primary" href="{% url 'generators:generator-delete' use_area=instance %}">Удалить</a>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

generators/templates/generators/script_generator.html
{% load static %}

<script type="text/javascript">

  function call_generator(request_parameter) {
    $.ajax({
      url: "{% url 'generators:ajax-generate' %}",
      data: {'use_area': request_parameter},
      success: function(data) {
          var el = document.getElementById("gen_input");
          console.log('Result is:'+data);
          el.value = String(data);
      }
    });
  }

</script>