archive/urls.py
from django.urls import path
from .views import archive_view

app_name = 'archive'
urlpatterns = [
    path('', archive_view, name='archive'),
]

export/urls.py
from django.urls import path

from export.views import protocol_list, protocol_address

app_name = 'export'
urlpatterns = [
    path('protocol_list/', protocol_list, name='protocol-list'),
    path('protocol_address/<int:protocol_id>/', protocol_address, name='protocol-address')
]

tekhnoritm_web/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import start_app
from django.conf.urls.static import static
from django.conf import settings
from .views import ajax_alarms, ajax_mark_as_red
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', start_app, name='start-app'),
    path('favicon.ico', RedirectView.as_view(url='/static/custom/favicon.ico'), name='favicon'),
    path('order_control/', include('order_control.urls')),
    path('rpn_searcher/', include('rpn_searcher.urls')),
    path('archive/', include('archive.urls')),
    path('laboratory/', include('laboratory.urls')),
    path('inspection/', include('inspection.urls')),
    path('orders/', include('orders.urls')),
    path('references/', include('references.urls')),
    path('generators/', include('generators.urls')),
    path('int_messages/', include('int_messages.urls')),
    path('site_admin/', include('site_admin.urls')),
    path('accounts/', include('accounts.urls')),
    path('workflow/', include('workflow.urls')),
    path('export', include('export.urls')),
    path('alarms/', ajax_alarms, name='ajax-alarm'),
    path('marks/', ajax_mark_as_red, name='ajax-mark-as-red'),
    path('admin/', admin.site.urls),
    re_path(r'^celery-progress/', include('celery_progress.urls')),  # the endpoint is configurable
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

archive/models.py
from django.db import models
import datetime
from orders.models import Order, Task, ExecutionPlan, Card

# Create your models here.


class ArchiveObject(models.Model):
    create_date = models.DateField(verbose_name='Дата архивации', default=datetime.date.today)
    ref_order = models.ForeignKey(to=Order,
                                  verbose_name='Заявка',
                                  on_delete=models.CASCADE,
                                  null=False,
                                  related_name='order_object')
    ref_task = models.ForeignKey(to=Task,
                                 verbose_name='Заявка',
                                 on_delete=models.CASCADE,
                                 null=False,
                                 related_name='task_object')
    ref_execution = models.ForeignKey(to=ExecutionPlan,
                                      verbose_name='Заявка',
                                      on_delete=models.CASCADE,
                                      null=False,
                                      related_name='execution_object')
    ref_card = models.ForeignKey(to=Card,
                                 verbose_name='Заявка',
                                 on_delete=models.CASCADE,
                                 null=False,
                                 related_name='card_object')
    doc_context = models.TextField(max_length=8192, blank=True, null=True)

archive/forms.py
from django import forms
from .models import ArchiveObject


class ArchiveForm(forms.Form):

    from_date = forms.DateField(required=True, widget=forms.DateInput(
        format='%d.%m.%Y',
        attrs={'placeholder': 'Искать с'}
    ),
        input_formats=['%d.%m.%Y',]
    )

    to_date = forms.DateField(required=True, widget=forms.DateInput(
        format='%d.%m.%Y',
        attrs={'placeholder': 'Искать до'}
    ),
        input_formats=['%d.%m.%Y',]
    )

    order_context = forms.CharField(max_length=128,
                                    help_text='Поиск по заявочной информации: номер заявки, заявитель, регион',
                                    required=False)
    task_context = forms.CharField(max_length=128,
                                   help_text='Поиск по внутренней информации: подразделение, тип задачи',
                                   required=False)
    execution_context = forms.CharField(max_length=128,
                                        help_text='Поиск внутри подразделения: внутр.исполнитель, внеш.исполнитель, цель',
                                        required=False)
    card_context = forms.CharField(max_length=128,
                                   help_text='Контекст документа: название, номер, заголовок, тип',
                                   required=False)

archive/views.py
from django.shortcuts import render
from django.db.models import Q
from .forms import ArchiveForm
from .models import ArchiveObject
from orders.models import Card

# Create your views here.


def archive_view(request):
    if request.method == 'POST':
        form = ArchiveForm(request.POST)
        context = {'form': form}
        if form.is_valid():
            search_result = ArchiveObject.objects.all()
            if form.cleaned_data.get('from_date', False):
                search_result = search_result.filter(create_date__gte=form.cleaned_data['from_date'])
            if form.cleaned_data.get('to_date', False):
                search_result = search_result.filter(create_date__lte=form.cleaned_data['to_date'])
            if form.cleaned_data.get('order_context', False):
                search_result = search_result.filter(Q(ref_order__order_id__icontains=form.cleaned_data['order_context']) |
                                     Q(ref_order__ext_order_id__icontains=form.cleaned_data['order_context']) |
                                     Q(ref_order__client__short_name__icontains=form.cleaned_data['order_context']) |
                                     Q(ref_order__client__long_name__icontains=form.cleaned_data['order_context']) |
                                     Q(ref_order__region__contains=form.cleaned_data['order_context']))
            if form.cleaned_data.get('task_context', False):
                search_result = search_result.filter(Q(ref_task__task_id__contains=form.cleaned_data['task_context']) |
                                     Q(ref_task__distribution_dep__description__icontains=form.cleaned_data['task_context']) |
                                     Q(ref_task__distribution_dep__name__contains=form.cleaned_data['task_context']) |
                                     Q(ref_task__task_type__contains=form.cleaned_data['task_context']))
            if form.cleaned_data.get('execution_context', False):
                search_result = search_result.filter(Q(ref_execution__int_executor__description__icontains=form.cleaned_data['execution_context']) |
                                     Q(ref_execution__int_executor__name__icontains=form.cleaned_data['execution_context']) |
                                     Q(ref_execution__ext_executor__icontains=form.cleaned_data['execution_context']) |
                                     Q(ref_execution__target__icontains=form.cleaned_data['execution_context']))
            if form.cleaned_data.get('card_context', False):
                search_result = search_result.filter(Q(ref_card__object_full_name__icontains=form.cleaned_data['card_context']) |
                                     Q(ref_card__doc_no__icontains=form.cleaned_data['card_context']) |
                                     Q(ref_card__doc_type__icontains=form.cleaned_data['card_context']) |
                                     Q(ref_card__doc_title__icontains=form.cleaned_data['card_context']) |
                                     Q(ref_card__doc_base__icontains=form.cleaned_data['card_context']))

            if search_result is not None:
                search_result = search_result.order_by('ref_order_id', 'ref_task_id', 'ref_execution_id', 'ref_card_id')
            context['search_result'] = search_result
    else:
        form = ArchiveForm()
        context = {'form': form}
    return render(request, 'archive/index.html', context=context)

archive/templates/archive/index.html
<!-- client_list.html -->

{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Begin Page Content -->
    <div class="container-fluid">

      <!-- Page Heading -->
      <h1 class="h1 mb-2 text-gray-800">А-Р-Х-И-В</h1>

      <form class="user" name="form" id="id_form" method="POST">
          {% csrf_token %}
          {% include 'archive/search_form.html' %}
      </form>

      {% include 'archive/results.html' %}

    </div>
    <!-- /.container-fluid -->

{% endblock content %}

archive/templates/archive/search_form.html
{% load static %}

<div class="container">

    <h3 class="text-uppercase">СФОРМИРУЙТЕ ПОИСКОВЫЙ ЗАПРОС:</h3>

    <div class="row">
        <div class="form-group m-0 col-12">
            <div class="form-row">
                <div class="col-6">
                    <span class="text-primary">Укажите временной диапазон:</span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-12">
                  <div class="row m-1">
                    <div class="col-2">
                        <span class="text-secondary">Начальная дата:</span>
                    </div>
                    <div class="col-3">
                        <span class="text-danger">{{ form.from_date.errors }}</span>
                        {{ form.from_date }}
                        {% if form.from_date.help_text %}
                        <p class="help font-italic small">*{{ form.from_date.help_text|safe }}</p>
                        {% endif %}
                    </div>
                  </div>
                  <div class="row m-1">
                    <div class="col-2">
                        <span class="text-secondary">Конечная дата:</span>
                    </div>
                    <div class="col-3">
                        <span class="text-danger">{{ form.to_date.errors }}</span>
                        {{ form.to_date }}
                        {% if form.to_date.help_text %}
                        <p class="help font-italic small">*{{ form.to_date.help_text|safe }}</p>
                        {% endif %}
                    </div>
                  </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-3">
                    <span class="text-primary">Контекст заявки:</span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-12">
                    <span class="text-danger">{{ form.order_context.errors }}</span>
                    <input type="text" class="form-control" id="id_order_context" name="order_context" placeholder="Текст для поиска" value="{{ form.initial.order_context }}">
                    {% if form.order_context.help_text %}
                    <p class="help font-italic small">*{{ form.order_context.help_text|safe }}</p>
                    {% endif %}
                </div>
            </div>
            <div class="form-row">
                <div class="col-3">
                    <span class="text-primary">Контекст внутренней заявки:</span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-12">
                    <span class="text-danger">{{ form.task_context.errors }}</span>
                    <input type="text" class="form-control" id="id_task_context" name="task_context" placeholder="Текст для поиска" value="{{ form.initial.task_context }}">
                    {% if form.task_context.help_text %}
                    <p class="help font-italic small">*{{ form.task_context.help_text|safe }}</p>
                    {% endif %}
                </div>
            </div>
            <div class="form-row">
                <div class="col-3">
                    <span class="text-primary">Контекст задачи:</span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-12">
                    <span class="text-danger">{{ form.execution_context.errors }}</span>
                    <input type="text" class="form-control" id="id_execution_context" name="execution_context" placeholder="Текст для поиска" value="{{ form.initial.execution_context }}">
                    {% if form.execution_context.help_text %}
                    <p class="help font-italic small">*{{ form.execution_context.help_text|safe }}</p>
                    {% endif %}
                </div>
            </div>
            <div class="form-row">
                <div class="col-3">
                    <span class="text-primary">Контекст объекта:</span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-12">
                    <span class="text-danger">{{ form.card_context.errors }}</span>
                    <input type="text" class="form-control" id="id_card_context" name="card_context" placeholder="Текст для поиска" value="{{ form.initial.card_context }}">
                    {% if form.card_context.help_text %}
                    <p class="help font-italic small">*{{ form.card_context.help_text|safe }}</p>
                    {% endif %}
                </div>
            </div>
        </div>
        <input class="btn btn-primary btn-user btn-block" type="submit" value="Поиск" />
    </div>


    <script type="text/javascript">
        $('#id_from_date').datepicker({
          uiLibrary: 'bootstrap4',
          format: 'dd.mm.yyyy'
        });
        $('#id_to_date').datepicker({
          uiLibrary: 'bootstrap4',
          format: 'dd.mm.yyyy'
        });
    </script>

</div>