export/urls.py
from django.urls import path

from export.views import protocol_list, protocol_address

app_name = 'export'
urlpatterns = [
    path('protocol_list/', protocol_list, name='protocol-list'),
    path('protocol_address/<int:protocol_id>/', protocol_address, name='protocol-address')
]

int_messages/urls.py
from django.urls import path, include
from .views import show_messages, create_message, detail_message, answer_message, close_topic, detail_alert

app_name = 'int_messages'
urlpatterns = [
    path('create/', create_message, name='message-create'),
    path('detail/<int:message_id>/<slug:parent_box>/', detail_message, name='message-detail'),
    path('alert_detail/<int:alert_id>/', detail_alert, name='alert-detail'),
    path('answer/', answer_message, name='message-answer'),
    path('close_message/<slug:ticket_id>/<str:parent_box>/', close_topic, name='topic-close'),
    path('show/<str:box>/<slug:type>/<slug:message>/', show_messages, name='message-list'),
]

order_control/urls.py
from django.urls import path, include
from .views import (
    show_target_list,
    control_config,
    add_person_to_alert,
    delete_person,
    delete_card,
    control_list,
    control_division,
    control_kind,
    kind_objects,
    control_executor,
    control_card,
    ajax_search_card,
)

app_name = 'order_control'
urlpatterns = [
    path('', show_target_list, name='target-list'),
    path('kind_objects/<str:action_id>/', kind_objects, name='kind-objects'),
    path('target_list_alert/<str:alert_message>/', show_target_list, name='target-list-alert'),
    path('control_list/', control_list, name='control-list'),
    path('control_division/', control_division, name='control-division'),
    path('control_kind/', control_kind, name='control-kind'),
    path('control_card/', control_card, name='control-card'),
    path('control_executor/', control_executor, name='control-executor'),
    path('config/<str:task_id>/', control_config, name='control-config'),
    path('add_person/', add_person_to_alert, name='add-person-to-alert'),
    path('delete_person/', delete_person, name='delete-person'),
    path('delete_card/<str:card_id>/', delete_card, name='delete-card'),
    path('ajax_search_card/', ajax_search_card, name='ajax-card-search'),
]

tekhnoritm_web/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import start_app
from django.conf.urls.static import static
from django.conf import settings
from .views import ajax_alarms, ajax_mark_as_red
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', start_app, name='start-app'),
    path('favicon.ico', RedirectView.as_view(url='/static/custom/favicon.ico'), name='favicon'),
    path('order_control/', include('order_control.urls')),
    path('rpn_searcher/', include('rpn_searcher.urls')),
    path('archive/', include('archive.urls')),
    path('laboratory/', include('laboratory.urls')),
    path('inspection/', include('inspection.urls')),
    path('orders/', include('orders.urls')),
    path('references/', include('references.urls')),
    path('generators/', include('generators.urls')),
    path('int_messages/', include('int_messages.urls')),
    path('site_admin/', include('site_admin.urls')),
    path('accounts/', include('accounts.urls')),
    path('workflow/', include('workflow.urls')),
    path('export', include('export.urls')),
    path('alarms/', ajax_alarms, name='ajax-alarm'),
    path('marks/', ajax_mark_as_red, name='ajax-mark-as-red'),
    path('admin/', admin.site.urls),
    re_path(r'^celery-progress/', include('celery_progress.urls')),  # the endpoint is configurable
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order_control/models.py
from django.db import models
from references.models import DefaultTasks
from accounts.models import Profile

# Create your models here.


class ControlConfig(models.Model):
    ref_task = models.ForeignKey(to=DefaultTasks,
                                 verbose_name='Задача',
                                 on_delete=models.CASCADE)
    is_warn_control = models.BooleanField(verbose_name='Желтый контроль включен', default=False)
    is_dang_control = models.BooleanField(verbose_name='Красный контроль включен', default=False)
    warn_days = models.IntegerField(verbose_name='Дней до включения', null=True, blank=True)
    dang_days = models.IntegerField(verbose_name='Дней до включения', null=True, blank=True)
    is_warn_alert = models.BooleanField(verbose_name='Оповещать (желтый)', default=False)
    is_dang_alert = models.BooleanField(verbose_name='Оповещать (красный)', default=False)
    warn_alert_type = models.IntegerField(verbose_name='Тип оповещения (желтый)', default=1) # 1 - однократно, 2 - каждый день
    dang_alert_type = models.IntegerField(verbose_name='Тип оповещения (красный)',
                                          default=1)  # 1 - однократно, 2 - каждый день

    @staticmethod
    def get_object_by_task(task):
        return ControlConfig.objects.filter(ref_task=task).first()

    @staticmethod
    def get_object_by_tasktype_target(tasktype, target):
        return ControlConfig.objects.filter(ref_task__task_type=tasktype).filter(ref_task__target=target).first()


class AlertPersonality(models.Model):
    ref_task = models.ForeignKey(to=ControlConfig,
                                 verbose_name='Тип контроля',
                                 on_delete=models.CASCADE)
    ref_profile = models.ForeignKey(to=Profile,
                                    verbose_name='Сотрудник',
                                    on_delete=models.CASCADE)

    @staticmethod
    def get_alerts_by_task(task):
        return AlertPersonality.objects.filter(ref_task=task)

order_control/forms.py
from django import forms
from order_control.models import ControlConfig
from .choices import ALERT_TYPES, EXECUTOR_TYPES, SEARCH_TYPES


class ControlConfigForm(forms.ModelForm):
    class Meta:
        model = ControlConfig
        fields = ['ref_task', 'is_warn_control', 'is_dang_control', 'warn_days', 'dang_days', 'is_warn_alert',
                  'is_dang_alert', 'warn_alert_type', 'dang_alert_type']
        widgets = {
            'warn_alert_type': forms.RadioSelect(choices=ALERT_TYPES),
            'dang_alert_type': forms.RadioSelect(choices=ALERT_TYPES),
            'ref_task': forms.HiddenInput(),
        }
        labels = {
            'is_warn_control': 'Включить контроль',
            'is_dang_control': 'Включить контроль',
            'warn_days': 'Дней спустя',
            'dang_days': 'Дней спустя',
            'is_warn_alert': 'Включить оповещение',
            'is_dang_alert': 'Включить оповещение',
            'warn_alert_type': 'Тип оповещения',
            'dang_alert_type': 'Тип оповещения',
        }


class StandardRequestForm(forms.Form):
    use_region = forms.BooleanField(label='Учесть регион', required=False)
    region = forms.CharField(label='', required=False)
    target = forms.CharField(label='Цель', required=False)
    search_text = forms.CharField(label='Поисковый запрос', required=False)
    type_search = forms.CharField(label='Тип поиска', required=False)
    only_warning = forms.BooleanField(label='Только горящие', required=False)
    executor = forms.IntegerField(required=False)
    int_executor = forms.CharField(max_length=256, required=False)
    ext_executor = forms.CharField(max_length=256, required=False)

    widgets = {
        'region': forms.Select(attrs={'placeholder': 'Выберите регион...'}),
        'target': forms.Select(),
        'executor': forms.Select(choices=EXECUTOR_TYPES),
        'type_search': forms.RadioSelect(choices=SEARCH_TYPES),
    }

order_control/views.py
from django.shortcuts import render, get_object_or_404, redirect
from references.models import DefaultTasks, Region
from accounts.models import Profile, Department
from .models import ControlConfig, AlertPersonality
from orders.models import Task, ExecutionPlan, TARGET_DOC_DICT, Card
from .forms import ControlConfigForm, StandardRequestForm
from django.db.models import Q
from functools import reduce
from operator import and_
import datetime
from accounts.choices import USER_REGION

# Create your views here.


def show_target_list(request, alert_message=None):
    tasks = DefaultTasks.objects.all().order_by('task_type', 'position')
    context = {
        'tasks': tasks,
        'alert_message': alert_message,
    }
    return render(request, 'order_control/target_list.html', context)


def control_config(request, task_id):
    task = get_object_or_404(DefaultTasks, id=task_id)
    control_card = ControlConfig.get_object_by_task(task)
    alert_message = None
    if request.method == 'POST':
        form = ControlConfigForm(request.POST, instance=control_card)
        if form.is_valid():
            form.save()
            alert_message = 'Настройки контроля задачи были успешно обновлены!'
    else:
        if not control_card:
            control_card = ControlConfig.objects.create(ref_task=task)
            control_card.save()
    form = ControlConfigForm(instance=control_card)
    persons = Profile.objects.filter(~Q(position='Не_определено')).filter(is_new=False)
    person_list = AlertPersonality.objects.filter(ref_task=control_card)

    context = {
        'control_card': control_card,
        'persons': persons,
        'person_list': person_list,
        'form': form,
        'alert_message': alert_message,
        'task_id': task.id,
    }

    return render(request, 'order_control/config_card.html', context)


def add_person_to_alert(request):
    task_id = request.GET['task_id']
    person_id = request.GET['person_id']
    task = get_object_or_404(ControlConfig, id=task_id)
    person = get_object_or_404(Profile, id=person_id)

    if_exist = AlertPersonality.objects.filter(ref_task=task, ref_profile=person)
    if not if_exist:
        new_alert = AlertPersonality.objects.create(ref_task=task, ref_profile=person)
        new_alert.save()

    persons = Profile.objects.filter(~Q(position='Не_определено')).filter(is_new=False)
    person_list = AlertPersonality.objects.filter(ref_task=task)
    context = {
        'persons': persons,
        'person_list': person_list,
    }

    return render(request, 'order_control/persons_to_alert.html', context)


def delete_person(request):
    ap_id = request.GET['alert_personality_id']
    ap = get_object_or_404(AlertPersonality, id=ap_id)
    task = ap.ref_task

    ap.delete()

    persons = Profile.objects.filter(~Q(position='Не_определено')).filter(is_new=False)
    person_list = AlertPersonality.objects.filter(ref_task=task)
    context = {
        'persons': persons,
        'person_list': person_list,
    }

    return render(request, 'order_control/persons_to_alert.html', context)


def delete_card(request, card_id):
    cc = get_object_or_404(ControlConfig, id=card_id)
    task_target = cc.ref_task.target
    cc.delete()
    return redirect('order_control:target-list-alert', alert_message='Контроль задачи '+task_target+' был успешно удален!')


def control_list(request):
    return render(request, 'order_control/control_list.html')


def control_division(request):
    context = {}
    if request.method == 'POST':
        form = StandardRequestForm(request.POST)
        if form.is_valid():
            sq = Task.objects.filter(accept_date__isnull=False).filter(close_date__isnull=True)
            if form.cleaned_data['use_region']:
                if form.cleaned_data['region']:
                    selected_region = get_object_or_404(Region, id=form.cleaned_data['region'])
                    sq = sq.filter(ref_order__region=selected_region.short_name)
                    context['selected_region'] = selected_region
            if form.cleaned_data['only_warning']:
                now = datetime.date.today()
                warn_date = now + datetime.timedelta(days=7)
                sq = sq.filter(dead_line__lte=warn_date)
            results = sq.order_by('dead_line')
            context['results'] = results
            context['form'] = form
    else:
        context = {
            'form': StandardRequestForm(initial={
                'use_region': False,
                'only_warning': False
            }),
        }

    context['regions'] = Region.objects.all()

    return render(request, 'order_control/control_division.html', context)


def control_kind(request):
    context = {}
    if request.method == 'POST':
        form = StandardRequestForm(request.POST)
        if form.is_valid():
            sq = ExecutionPlan.objects.filter(start_date__isnull=False).filter(stop_date__isnull=True)
            cc = None
            if form.cleaned_data['use_region']:
                if form.cleaned_data['region']:
                    selected_region = get_object_or_404(Region, id=form.cleaned_data['region'])
                    sq = sq.filter(ref_task__ref_order__region=selected_region.short_name)
                    context['selected_region'] = selected_region
            if form.cleaned_data['target']:
                dt = DefaultTasks.objects.filter(id=form.cleaned_data['target']).first()
                cc = ControlConfig.get_object_by_task(dt)
                context['selected_target'] = dt
                if dt:
                    sq = sq.filter(target=dt.target).filter(ref_task__task_type=dt.task_type)
            if form.cleaned_data['only_warning']:
                if cc is not None:
                    sq = sq.filter(start_date__lte=datetime.date.today()-datetime.timedelta(days=cc.warn_days))
            results = sq.order_by('start_date')
            context['results'] = results
            context['form'] = form
    else:
        context = {
            'form': StandardRequestForm(initial={
                'use_region': False,
            }),
        }

    context['regions'] = Region.objects.all()
    tasks = DefaultTasks.objects.all().order_by('task_type', 'position')
    context['tasks'] = tasks

    return render(request, 'order_control/control_kind.html', context)


def control_card(request):
    context = {
        'regions': USER_REGION,
        'form': StandardRequestForm(),
    }
    return render(request, 'order_control/control_card.html', context)


def ajax_search_card(request):
    search_line = request.GET['search_line']
    type_search = request.GET['type_search']
    region = request.GET['region']
    if search_line:
        region_qs = None
        if region != '0':
            region_qs = reduce(and_, (Q(ref_action__ref_task__ref_order__region=region),))
        if type_search == 'strong':
            if region_qs is not None:
                cards = Card.objects.filter(Q(object_full_name__icontains=search_line) | Q(
                    doc_title__icontains=search_line)).filter(region_qs).order_by(
                    '-start_date')[:20]
            else:
                cards = Card.objects.filter(Q(object_full_name__icontains=search_line) | Q(
                    doc_title__icontains=search_line)).order_by(
                    '-start_date')[:20]
        else:
            ofn_qs = reduce(and_, (Q(object_full_name__icontains=x) for x in search_line.split()))
            dt_qs = reduce(and_, (Q(doc_title__icontains=x) for x in search_line.split()))
            db_qs = reduce(and_, (Q(doc_base__icontains=x) for x in search_line.split()))
            if region_qs is not None:
                cards = Card.objects.filter(ofn_qs | dt_qs | db_qs).filter(region_qs).order_by('-start_date')[:20]
            else:
                cards = Card.objects.filter(ofn_qs | dt_qs | db_qs).order_by('-start_date')[:20]

    else:
        cards = None
    context = {
        'cards': cards,
        'regions': USER_REGION,
    }
    return render(request, 'order_control/card_list_ajax.html', context)


def kind_objects(request, action_id):
    action = get_object_or_404(ExecutionPlan, id=action_id)
    cards = Card.get_cards_by_action(action)

    context = {
        'action': action,
        'cards': cards,
    }

    return render(request, 'order_control/cards.html', context)


EXT_EXECUTORS_DICT = {
    'RPN': 'Роспотребнадзор',
    'FMBA': 'ФМБА',
    'OWNER': 'Владелец ПРТО',
    'CLIENT': 'Заказчик',
    'OTHER': 'Иное',
}


def control_executor(request):
    context = {}
    if request.method == 'POST':
        form = StandardRequestForm(request.POST)
        if form.is_valid():
            sq = ExecutionPlan.objects.filter(start_date__isnull=False).filter(stop_date__isnull=True)
            if form.cleaned_data['use_region']:
                if form.cleaned_data['region']:
                    selected_region = get_object_or_404(Region, id=form.cleaned_data['region'])
                    sq = sq.filter(ref_task__ref_order__region=selected_region.short_name)
                    context['selected_region'] = selected_region
            if form.cleaned_data['executor']:
                context['selected_executor'] = form.cleaned_data['executor']
                if form.cleaned_data['executor'] == 1:
                    dep = get_object_or_404(Department, name=form.cleaned_data['int_executor'])
                    context['selected_int'] = dep
                    sq = sq.filter(int_executor=dep)
                elif form.cleaned_data['executor'] == 2:
                    context['selected_ext_key'] = form.cleaned_data['ext_executor']
                    context['selected_ext_value'] = EXT_EXECUTORS_DICT[form.cleaned_data['ext_executor']]
                    sq = sq.filter(ext_executor=form.cleaned_data['ext_executor'])
            results = sq.order_by('start_date')
            context['results'] = results
            context['form'] = form

order_control/templates/order_control/config_card.html
<!-- config_card.html -->

{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Карточка настрйоки контроля задачи</h1>
            <a href="{% url 'int_messages:message-create' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Написать сообщение</a>
          </div>

          <div>
              {% if success %}
              <p class="text-success">{{ success }}</p>
              {% endif %}
          </div>

<!-- End of Page Heading -->


<div class="container">
    <div class="row">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
              <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                  <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                      ТИП: {{ control_card.ref_task.task_type }}&nbsp;&nbsp;ЦЕЛЬ: {{ control_card.ref_task.target }}
                  </div>
                  <div class="h6 mb-0 font-weight-bold text-gray-600">{{ control_card.ref_task.get_target_description }}</div>
                  <div class="text-xs font-weight-bold text-primary text-uppercase mt-2">
                      <a href="{% url 'order_control:target-list' %}"><i class="fas fa-share-square fa-1x text-success"></i> назад к списку</a>
                  </div>
                </div>
                <div class="col-auto">
                  <i class="fas fa-calendar fa-2x text-gray-300"></i>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    {% if alert_message %}
        <h4 class="text-success">{{ alert_message }}</h4>
    {% endif %}
    <div class="card shadow m-2">
        <form class="user" id="main_form" method="POST" name="form">
          {% csrf_token %}
            <input type="hidden" id="id_ref_task" name="ref_task" value="{{ task_id }}">
            <nav>
              <div class="nav nav-tabs" id="nav-tab" role="tablist">
                <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-warn" role="tab" aria-controls="nav-warn" aria-selected="true"><span class="text-warning">Желтый уровень</span></a>
                <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-dang" role="tab" aria-controls="nav-dang" aria-selected="false"><span class="text-danger">Красный уровень</span></a>
              </div>
            </nav>
            <div class="tab-content" id="nav-tabContent">
              <div class="tab-pane fade show active" id="nav-warn" role="tabpanel" aria-labelledby="nav-home-tab">
                <div class="form-group m-3 col-12">
                    {{ form.is_warn_control.label }}
                    <span class="text-danger">{{ form.is_warn_control.errors }}</span>
                    {{ form.is_warn_control }}
                    {% if form.is_warn_control.help_text %}
                    <p class="help font-italic small">*{{ form.is_warn_control.help_text|safe }}</p>
                    {% endif %}
                </div>
                <div class="form-group m-3 col-12">
                    {{ form.warn_days.label }}
                    <span class="text-danger">{{ form.warn_days.errors }}</span>
                    {{ form.warn_days }}
                    {% if form.warn_days.help_text %}
                    <p class="help font-italic small">*{{ form.warn_days.help_text|safe }}</p>
                    {% endif %}
                </div>
                <div class="form-group m-3 col-12">
                    {{ form.is_warn_alert.label }}
                    <span class="text-danger">{{ form.is_warn_alert.errors }}</span>
                    {{ form.is_warn_alert }}
                    {% if form.is_warn_alert.help_text %}
                    <p class="help font-italic small">*{{ form.is_warn_alert.help_text|safe }}</p>
                    {% endif %}
                </div>
                <div class="form-group m-3 col-12">
                    {{ form.warn_alert_type.label }}
                    <span class="text-danger">{{ form.warn_alert_type.errors }}</span>
                    {{ form.warn_alert_type }}
                    {% if form.warn_alert_type.help_text %}
                    <p class="help font-italic small">*{{ form.warn_alert_type.help_text|safe }}</p>
                    {% endif %}
                </div>
              </div>
              <div class="tab-pane fade" id="nav-dang" role="tabpanel" aria-labelledby="nav-profile-tab">
                <div class="form-group m-3 col-12">
                    {{ form.is_dang_control.label }}
                    <span class="text-danger">{{ form.is_dang_control.errors }}</span>
                    {{ form.is_dang_control }}
                    {% if form.is_dang_control.help_text %}
                    <p class="help font-italic small">*{{ form.is_dang_control.help_text|safe }}</p>
                    {% endif %}
                </div>
                <div class="form-group m-3 col-12">
                    {{ form.dang_days.label }}
                    <span class="text-danger">{{ form.dang_days.errors }}</span>
                    {{ form.dang_days }}
                    {% if form.dang_days.help_text %}
                    <p class="help font-italic small">*{{ form.dang_days.help_text|safe }}</p>
                    {% endif %}
                </div>
                <div class="form-group m-3 col-12">
                    {{ form.is_dang_alert.label }}
                    <span class="text-danger">{{ form.is_dang_alert.errors }}</span>
                    {{ form.is_dang_alert }}
                    {% if form.is_dang_alert.help_text %}
                    <p class="help font-italic small">*{{ form.is_dang_alert.help_text|safe }}</p>
                    {% endif %}
                </div>
                <div class="form-group m-3 col-12">
                    {{ form.dang_alert_type.label }}
                    <span class="text-danger">{{ form.dang_alert_type.errors }}</span>
                    {{ form.dang_alert_type }}
                    {% if form.dang_alert_type.help_text %}
                    <p class="help font-italic small">*{{ form.dang_alert_type.help_text|safe }}</p>
                    {% endif %}
                </div>
              </div>
            </div>
            <div id="persons_list" class="m-2">
                {% include 'order_control/persons_to_alert.html' %}
            </div>
          <div class="m-2">
              <input class="btn btn-primary btn-user btn-block" type="submit" value="Сохранить" />
              <hr />
              <a href="{% url 'order_control:delete-card' card_id=control_card.id %}" class="small text-warning">* Удалить контроль задачи</a>
          </div>
        </form>
    </div>
</div>

<script type="text/javascript">

    function add_person(person_id) {
        $.ajax({
          url: "{% url 'order_control:add-person-to-alert' %}",
          data: {'person_id': person_id,
                 'task_id': {{ control_card.id }}
          },
          success: function(data) {
             $('#persons_list').html(data);
          }
        });
    }

    function delete_person(alert_personality_id) {
        $.ajax({
          url: "{% url 'order_control:delete-person' %}",
          data: {'alert_personality_id': alert_personality_id},
          success: function(data) {
             $('#persons_list').html(data);
          }
        });
    }

</script>

{% endblock content %}

order_control/templates/order_control/control_list.html
<!-- control_list.html -->

{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Области контроля заявок</h1>
            <a href="{% url 'int_messages:message-create' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Написать сообщение</a>
          </div>

          <div>
              {% if success %}
              <p class="text-success">{{ success }}</p>
              {% endif %}
          </div>

<!-- End of Page Heading -->


<div class="container">
    <div class="row">
        <div class="card-body">
          {% if alert_message %}
            <h4 class="text-success">{{ alert_message }}</h4>
          {% endif %}
          <div class="table-responsive">
            <table class="table" id="dataTable" width="100%" cellspacing="0">
              <tbody>
                <tr>
                    <td class="m-2 p-2 align-middle"><img src="/static/img/division.png" class="img-profile rounded-circle img-thumbnail" alt="Subdivisions (Подразделения)">
                    <a class="ml-4" href="{% url 'order_control:control-division' %}"><span class="text-uppercase">Заявки в работе подразделений</span></a></td>
                <tr>
                    <td class="m-2 p-2 align-middle"><img src="/static/img/kind.png" class="img-profile rounded-circle img-thumbnail" alt="Task kind (Виды работ)">
                    <a class="ml-4" href="{% url 'order_control:control-kind' %}"><span class="text-uppercase">Контроль по видам работ</span></a></td>
                </tr>
                <tr>
                    <td class="m-2 p-2 align-middle"><img src="/static/img/executor.png" class="img-profile rounded-circle img-thumbnail" alt="Executors (Исполнители)">
                    <a class="ml-4" href="{% url 'order_control:control-executor' %}"><span class="text-uppercase">Контроль исполнителей</span></a></td>
                </tr>
                <tr>
                    <td class="m-2 p-2 align-middle"><img src="/static/img/objects.png" class="img-profile rounded-circle img-thumbnail" alt="Objects (Объектыв исследований)">
                    <a class="ml-4" href="{% url 'order_control:control-card' %}"><span class="text-uppercase">Контроль объектов исследований</span></a></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
    </div>
</div>

{% endblock content %}

order_control/templates/order_control/script_card_search.html
{% load static %}

<script type="text/javascript">
  const search_input = $("#search_input")
  const delay_by_in_ms = 700
  let scheduled_function = false

  function call_search(request_parameter) {
    var radioValue = $("input[name='type_search']:checked").val();
    $.ajax({
      url: "{% url 'order_control:ajax-card-search' %}",
      data: {'search_line': request_parameter,
             'type_search': radioValue,
             'region': document.getElementById('id_region').value},
      success: function(data) {
        $('#list_content').html(data);
      }
    });
  }

  $(document).ready(function ($) {
    call_search('');
  });

  search_input.on('keyup', function () {
    const request_parameter = $(this).val() // value of user_input: the HTML element with ID user-input

    if (scheduled_function) {
        clearTimeout(scheduled_function)
    }

    scheduled_function = setTimeout(call_search, delay_by_in_ms, request_parameter)
  })
</script>

order_control/templates/order_control/target_list.html
<!-- target_list.html -->

{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Выбор задачи для настройки контроля</h1>
            <a href="{% url 'int_messages:message-create' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Написать сообщение</a>
          </div>

          <div>
              {% if success %}
              <p class="text-success">{{ success }}</p>
              {% endif %}
          </div>

<!-- End of Page Heading -->


<div class="container">
    <div class="row">
        <div class="card-body">
          {% if alert_message %}
            <h4 class="text-success">{{ alert_message }}</h4>
          {% endif %}
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>Тип задачи</th>
                  <th>Код цели</th>
                  <th>Описание цели</th>
                </tr>
              </thead>
              <tbody>
                {% for instance in tasks %}
                <tr>
                    <td>{{ instance.task_type }}</td>
                    <td><a href="{% url 'order_control:control-config' task_id=instance.id %}"><strong>{{ instance.target }}</strong></a></td>
                    <td>{{ instance.get_target_description }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
    </div>
</div>

{% endblock content %}