export/urls.py
from django.urls import path

from export.views import protocol_list, protocol_address

app_name = 'export'
urlpatterns = [
    path('protocol_list/', protocol_list, name='protocol-list'),
    path('protocol_address/<int:protocol_id>/', protocol_address, name='protocol-address')
]

int_messages/urls.py
from django.urls import path, include
from .views import show_messages, create_message, detail_message, answer_message, close_topic, detail_alert

app_name = 'int_messages'
urlpatterns = [
    path('create/', create_message, name='message-create'),
    path('detail/<int:message_id>/<slug:parent_box>/', detail_message, name='message-detail'),
    path('alert_detail/<int:alert_id>/', detail_alert, name='alert-detail'),
    path('answer/', answer_message, name='message-answer'),
    path('close_message/<slug:ticket_id>/<str:parent_box>/', close_topic, name='topic-close'),
    path('show/<str:box>/<slug:type>/<slug:message>/', show_messages, name='message-list'),
]

tekhnoritm_web/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import start_app
from django.conf.urls.static import static
from django.conf import settings
from .views import ajax_alarms, ajax_mark_as_red
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', start_app, name='start-app'),
    path('favicon.ico', RedirectView.as_view(url='/static/custom/favicon.ico'), name='favicon'),
    path('order_control/', include('order_control.urls')),
    path('rpn_searcher/', include('rpn_searcher.urls')),
    path('archive/', include('archive.urls')),
    path('laboratory/', include('laboratory.urls')),
    path('inspection/', include('inspection.urls')),
    path('orders/', include('orders.urls')),
    path('references/', include('references.urls')),
    path('generators/', include('generators.urls')),
    path('int_messages/', include('int_messages.urls')),
    path('site_admin/', include('site_admin.urls')),
    path('accounts/', include('accounts.urls')),
    path('workflow/', include('workflow.urls')),
    path('export', include('export.urls')),
    path('alarms/', ajax_alarms, name='ajax-alarm'),
    path('marks/', ajax_mark_as_red, name='ajax-mark-as-red'),
    path('admin/', admin.site.urls),
    re_path(r'^celery-progress/', include('celery_progress.urls')),  # the endpoint is configurable
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

export/models.py
from django.db import models

# Create your models here.

export/forms.py
from django import forms

from export.choices import EXPORT_CHOICES


class ExportProtocolForm(forms.Form):
    action = forms.ChoiceField(choices=EXPORT_CHOICES,
                               widget=forms.Select(attrs={'class': 'form-control'}))
    from_date = forms.DateField(widget=forms.DateInput(
        format='%d.%m.%Y',
        attrs={'placeholder': 'Начальная дата'}
    ),
        input_formats=['%d.%m.%Y',], required=False
    )
    to_date = forms.DateField(widget=forms.DateInput(
        format='%d.%m.%Y',
        attrs={'placeholder': 'Конечная дата', 'class': 'form-control'}
    ),
        input_formats=['%d.%m.%Y',], required=False
    )


class ProtocolAddressFiasForm(forms.Form):
    address = forms.CharField(max_length=1024, required=False, widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    address_fias = forms.CharField(max_length=4096, widget=forms.HiddenInput())
    protocol_id = forms.IntegerField(widget=forms.HiddenInput())

export/views.py
import json

from django.contrib import messages
from django.core.exceptions import ValidationError
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from export.forms import ExportProtocolForm, ProtocolAddressFiasForm
from export.service import XMLGenerator, DadataClient
from inspection.models import Protocol


def protocol_list(request):
    protocols = Protocol.objects.filter(
        export_date__isnull=True).filter(
        export_exclude=False).order_by('-protocol_date')[:30]
    if request.method == 'POST':
        form = ExportProtocolForm(request.POST)
        if form.is_valid():
            action = form.cleaned_data['action']
            protocol_ids = request.POST.getlist('protocol')
            if action == 'generate':
                xml_class = XMLGenerator()
                dadata_class = DadataClient()
                xml = xml_class.generate(dadata_class.update_protocols(protocol_ids))
                output = 'protocols.xml'
                response = HttpResponse(xml, content_type='application/xml')
                response['Content-Disposition'] = f'attachment; filename={output}'
                return response
            elif action == 'exclude':
                protocols = list()
                for p_id in protocol_ids:
                    protocol = Protocol.objects.get(protocol_id=p_id)
                    protocol.export_exclude = True
                    protocol.save()
                    protocols.append(protocol)
                messages.add_message(request, messages.INFO, f'Исключено из экспорта <strong>{len(protocols)}</strong> протоколов!')
                protocols = Protocol.objects.filter(
                    export_date__isnull=True).filter(
                    export_exclude=False).order_by('-protocol_date')[:30]
            elif action == 'select':
                try:
                    from_date = form.cleaned_data['from_date']
                    to_date = form.cleaned_data['to_date']
                    protocols = Protocol.objects.filter(protocol_date__range=(from_date, to_date))
                    messages.add_message(request, messages.INFO, f'Выбрано <strong>{len(protocols)}</strong> документов!')
                except Exception as e:
                    print(str(e))
                    raise ValidationError('Даты не корректны', code='dates_invalid')
    else:
        form = ExportProtocolForm(initial={
            'action': 'generate',
        })
    context = {
        'form': form,
        'protocols': protocols,
    }
    return render(request, 'export/protocol_list.html', context)


def protocol_address(request, protocol_id):
    protocol = get_object_or_404(Protocol, protocol_id=protocol_id)
    if request.method == 'POST':
        form = ProtocolAddressFiasForm(request.POST)
        if form.is_valid():
            address_fias = form.cleaned_data['address_fias']
            obj = protocol.ref_object
            obj.address_fias = json.loads(address_fias)
            obj.save()
            protocol.refresh_from_db()
            messages.add_message(request, messages.INFO, 'Адрес был успешно обновлен в соответствии с базой ФИАС')
    else:
        form = ProtocolAddressFiasForm(initial={
            'protocol_id': protocol.protocol_id,
            'address': protocol.ref_object.address
        })

    context = {
        'form': form,
        'protocol': protocol,
    }
    return render(request, 'export/update_address.html', context)

export/templates/export/protocol_list.html
<!-- doc_generation.html -->

{% extends 'base.html' %}

{% block content %}
    <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Генерация XML-документа для Росаккредитации</h1>
            <a href="{% url 'int_messages:message-create' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Написать сообщение</a>
          </div>
    <!-- End of Page Heading -->

    <div class="container">

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">
                    {{ message|safe }}
                </div>
                {% endfor %}
            </ul>
        {% endif %}

        <form class="user" name="form" method="post">

            {% csrf_token %}

            {% if form.non_field_errors %}
              <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                  {{ error }}
                {% endfor %}
              </div>
            {% endif %}

          <div class="row">
            <div class="col-xl-6 col-md-9 mb-4">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row">
                    <div class="col mr-2">
                        {{ form.action.errors }}
                          {{ form.action }}
                        {% if form.action.help_text %}
                        <p class="help font-italic small">*{{ form.action.help_text|safe }}</p>
                        {% endif %}
                        <div class="form-row mt-2">
                            <div class="col">
                              {{ form.from_date.errors }}
                              {{ form.from_date }}
                              {% if form.from_date.help_text %}
                                <p class="help font-italic small">*{{ form.from_date.help_text|safe }}</p>
                              {% endif %}
                            </div>
                            <div class="col">
                              {{ form.to_date.errors }}
                              {{ form.to_date }}
                              {% if form.to_date.help_text %}
                                <p class="help font-italic small">*{{ form.to_date.help_text|safe }}</p>
                              {% endif %}
                            </div>
                      </div>
                      <div class="d-block">
                          <span class="text-secondary small">**Указание периода применяется ТОЛЬКО для действия выборки</span>
                      </div>
                      <div class="d-block">
                          <button type="submit" class="btn btn-primary">Выполнить</button>
                      </div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

            <div class="card shadow">
                <div class="card-body">
                  <div class="row">
                    <div class="col-xl-12 col-md-12 mb-2">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable">
                              <thead>
                                <tr>
                                  <th class="text-center"><input type="checkbox" onClick="toggle(this)" /> Выбрать ВСЕ<br/></th>
                                  <th>Номер протокола</th>
                                  <th>Дата протокола</th>
                                  <th>Дата измерения</th>
                                  <th>Наименование</th>
                                  <th>Дата экспорта</th>
                                  <th>Исключение</th>
                                  <th>Ошибка экспорта</th>
                                </tr>
                              </thead>
                              <tbody>
                                {% for protocol in protocols %}
                                <tr>
                                    <td class="text-center"><input type="checkbox" name="protocol" value="{{ protocol.protocol_id }}"></td>
                                    <td>{{ protocol.protocol_no }}</td>
                                    <td>{{ protocol.protocol_date|date:"d.m.Y" }}</td>
                                    <td>{{ protocol.action_date|date:"d.m.Y" }}</td>
                                    <td>{{ protocol.ref_object.name }}</td>
                                    <td>{{ protocol.export_date|date:"d.m.Y" }}</td>
                                    <td>
                                        {% if protocol.export_exclude %}
                                            <span class="text-warning">Исключен</span>
                                        {% else %}
                                            ---
                                        {% endif %}
                                    </td>
                                    <td>
                                        <span class="text-danger">{{ protocol.export_error|default_if_none:"" }}</span>
                                        <div class="d-block small"><a href="{% url 'export:protocol-address' protocol_id=protocol.protocol_id %}" target="_new">Обновить адрес (ФИАС)</a></div>
                                    </td>
                                </tr>
                                {% endfor %}
                              </tbody>
                            </table>
                        </div>
                    </div>
                  </div>
                </div>
            </div>

        </form>

    </div>

    <script type="text/javascript">

        $(document).ready(function() {
            $('#id_from_date').datepicker({
                uiLibrary: 'bootstrap4',
                format: 'dd.mm.yyyy'
            });
            $('#id_to_date').datepicker({
                uiLibrary: 'bootstrap4',
                format: 'dd.mm.yyyy'
            });
        });

        function toggle(source) {
          checkboxes = document.getElementsByName('protocol');
          for(let i=0, n=checkboxes.length;i<n;i++) {
            checkboxes[i].checked = source.checked;
          }
        }
    </script>

{% endblock %}

export/templates/export/update_address.html
<!-- update_address.html -->

{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Begin Page Content -->
    <div class="container-fluid">

      <!-- Page Heading -->
      <h1 class="h1 mb-2 text-gray-800">Поиск адреса в базе ФИАС</h1>

      {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">
                {{ message|safe }}
            </div>
            {% endfor %}
        </ul>
      {% endif %}

      <form class="user" name="main_form" id="id_main_form" method="POST">
          {% csrf_token %}

          {% if form.non_field_errors %}
              <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                  {{ error }}
                {% endfor %}
              </div>
          {% endif %}

          {{ form.protocol_id }}
          {{ form.address_fias }}

          <div class="form-group m-3 col-12">
            <span class="text-danger">{{ form.address.errors }}</span>
            <div id="fias_ok">
            </div>
            <input type="text" class="form-control" id="id_address" name="address" placeholder="Адреc размещения"
                   value="{{ protocol.ref_object.address }}">
            {% if form.address.help_text %}
            <p class="help font-italic small">*{{ form.address.help_text|safe }}</p>
            {% endif %}
          </div>
          <div class="form-group m-3 col-12">
              <input type="submit" value="Обновить">
          </div>
      </form>

    </div>
    <!-- /.container-fluid -->

    {% include 'inspection/dadata.html' %}

{% endblock content %}